name: PR Tests

on:
  pull_request:
    branches: [ master, main ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.42.x
          
      - name: Run tests
        run: deno test src/tests/
        
      - name: Check types
        run: deno check src/index.ts
        
      - name: Lint
        run: deno lint